apiVersion: v1
kind: Namespace
metadata:
  name: dev 
---
# Deployment Object 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student
  template:
    metadata:
      labels:
        app: student
    spec:
      containers:
      - name: student-container
        image: ravi2krishna/login-2603:student
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: student-service
  namespace: dev
spec:
  ports:
    # Accept traffic sent to port 80
    - name: http
      port: 80 # this is app running port 
      nodePort: 30009 # this is node running port 
  selector:
    # Loadbalance traffic across Pods matching this label selector
    app: student
  type: NodePort